.TH "Aleatorio" 3 "Quinta, 19 de Abril de 2018" "Version 1.0" "Projeto P1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aleatorio
.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "int \fBrandomizeDirecao\fP ()"
.br
.RI "volta um número aleatório entre 1 e 4 "
.ti -1c
.RI "int \fBrandomize30\fP ()"
.br
.RI "volta um número aleatório entre 0 e 30 "
.ti -1c
.RI "int \fBrandomize60\fP ()"
.br
.RI "volta um número aleatório entre 0 e 60 "
.ti -1c
.RI "int \fBrandomizePassageiros\fP ()"
.br
.RI "volta um número aleatório entre 1 e 5 "
.ti -1c
.RI "int \fBrandomizeCarga\fP ()"
.br
.RI "volta um número aleatório entre 10000 e 30000 "
.ti -1c
.RI "int \fBrandomizeID\fP ()"
.br
.RI "volta um número aleatório entre 1 e 300000 "
.ti -1c
.RI "String \fBrandomizeTipo\fP ()"
.br
.RI "volta um tipo de moto aleatória "
.in -1c
.SS "Atributos Protegidos"

.in +1c
.ti -1c
.RI "int \fBnumero\fP"
.br
.in -1c
.SH "Documentação dos métodos"
.PP 
.SS "int Aleatorio\&.randomize30 ()"

.PP
volta um número aleatório entre 0 e 30 
.SS "int Aleatorio\&.randomize60 ()"

.PP
volta um número aleatório entre 0 e 60 
.SS "int Aleatorio\&.randomizeCarga ()"

.PP
volta um número aleatório entre 10000 e 30000 
.SS "int Aleatorio\&.randomizeDirecao ()"

.PP
volta um número aleatório entre 1 e 4 
.SS "int Aleatorio\&.randomizeID ()"

.PP
volta um número aleatório entre 1 e 300000 
.SS "int Aleatorio\&.randomizePassageiros ()"

.PP
volta um número aleatório entre 1 e 5 
.SS "String Aleatorio\&.randomizeTipo ()"

.PP
volta um tipo de moto aleatória 
.SH "Documentação dos dados membro"
.PP 
.SS "int Aleatorio\&.numero\fC [protected]\fP"


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Projeto P1 a partir do código fonte\&.
