.TH "Caminhao" 3 "Quinta, 19 de Abril de 2018" "Version 1.0" "Projeto P1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Caminhao
.SH SYNOPSIS
.br
.PP
.PP
Derivada de \fBVeiculo\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBCaminhao\fP ()"
.br
.RI "construtor padrão com capacidade de carga aleatória "
.in -1c
.SS "Atributos Protegidos"

.in +1c
.ti -1c
.RI "int \fBcapacidadeCarga\fP"
.br
.in -1c
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "Caminhao\&.Caminhao ()"

.PP
construtor padrão com capacidade de carga aleatória chama construtor padrão da classe pai 
.SH "Documentação dos dados membro"
.PP 
.SS "int Caminhao\&.capacidadeCarga\fC [protected]\fP"


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Projeto P1 a partir do código fonte\&.
