.TH "Carro" 3 "Quinta, 19 de Abril de 2018" "Version 1.0" "Projeto P1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Carro
.SH SYNOPSIS
.br
.PP
.PP
Derivada de \fBVeiculo\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBCarro\fP ()"
.br
.RI "construtor padrão com número de passageiros aleatório "
.in -1c
.SS "Atributos Protegidos"

.in +1c
.ti -1c
.RI "int \fBnumPassageiros\fP"
.br
.in -1c
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "Carro\&.Carro ()"

.PP
construtor padrão com número de passageiros aleatório passa dados para o construtor padrão de veiculos 
.SH "Documentação dos dados membro"
.PP 
.SS "int Carro\&.numPassageiros\fC [protected]\fP"


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Projeto P1 a partir do código fonte\&.
