.TH "Colisoes" 3 "Quinta, 19 de Abril de 2018" "Version 1.0" "Projeto P1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Colisoes
.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBColisoes\fP ()"
.br
.RI "construtor padrão "
.ti -1c
.RI "String \fBgetTipo\fP (int i, int j)"
.br
.RI "retorna o tipo que está nas coordenadas entradas "
.ti -1c
.RI "int \fBgetID\fP (int i, int j)"
.br
.RI "retorna a ID que está nas coordenadas entradas "
.ti -1c
.RI "void \fBocupado\fP (int i, int j, String tipo, int ID)"
.br
.RI "popula a coordenada entrada com o tipo e ID desejado "
.ti -1c
.RI "void \fBrestaura\fP (int i, int j)"
.br
.in -1c
.SS "Atributos Protegidos"

.in +1c
.ti -1c
.RI "String \fBtipos\fP [][]"
.br
.ti -1c
.RI "int \fBid\fP [][]"
.br
.in -1c
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "Colisoes\&.Colisoes ()"

.PP
construtor padrão nova matriz de 30x60 para armazenar os tipos de veiculos
.PP
nova matriz de 30x60 para armazenar as IDs dos veiculos
.PP
inicializa as duas matrizes como vazias 
.SH "Documentação dos métodos"
.PP 
.SS "int Colisoes\&.getID (int i, int j)"

.PP
retorna a ID que está nas coordenadas entradas 
.SS "String Colisoes\&.getTipo (int i, int j)"

.PP
retorna o tipo que está nas coordenadas entradas 
.SS "void Colisoes\&.ocupado (int i, int j, String tipo, int ID)"

.PP
popula a coordenada entrada com o tipo e ID desejado 
.SS "void Colisoes\&.restaura (int i, int j)"

.SH "Documentação dos dados membro"
.PP 
.SS "int Colisoes\&.id[][]\fC [protected]\fP"

.SS "String Colisoes\&.tipos[][]\fC [protected]\fP"


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Projeto P1 a partir do código fonte\&.
