.TH "Legenda" 3 "Quinta, 19 de Abril de 2018" "Version 1.0" "Projeto P1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Legenda
.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "void \fBexibeLegenda\fP ()"
.br
.RI "Exibe o mundo sem nenhum veiculo, indicando as fabricas (é exibido por 5 segundos) "
.ti -1c
.RI "void \fBvoltaCarro\fP ()"
.br
.RI "volta o carro do terminal uma linha acima "
.ti -1c
.RI "void \fBpausaLegenda\fP ()"
.br
.RI "pausa a execução do programa por 5 segundos "
.ti -1c
.RI "void \fBvoltaComecoLegenda\fP ()"
.br
.RI "volta o carro para o inicio do mapa "
.in -1c
.SH "Documentação dos métodos"
.PP 
.SS "void Legenda\&.exibeLegenda ()"

.PP
Exibe o mundo sem nenhum veiculo, indicando as fabricas (é exibido por 5 segundos) 
.SS "void Legenda\&.pausaLegenda ()"

.PP
pausa a execução do programa por 5 segundos 
.SS "void Legenda\&.voltaCarro ()"

.PP
volta o carro do terminal uma linha acima 
.SS "void Legenda\&.voltaComecoLegenda ()"

.PP
volta o carro para o inicio do mapa 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Projeto P1 a partir do código fonte\&.
