.TH "Main" 3 "Quinta, 19 de Abril de 2018" "Version 1.0" "Projeto P1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main
.SH SYNOPSIS
.br
.PP
.SS "Membros públicos estáticos"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String argv[])"
.br
.in -1c
.SH "Documentação dos métodos"
.PP 
.SS "static void Main\&.main (String argv[])\fC [static]\fP"
cria o objeto mundo
.PP
novo vetor dinâmico para armazenar os carros
.PP
novo vetor dinâmico para armazenar os caminhões
.PP
novo vetor dinâmico para armazenar as motos
.PP
vetor que salva a quantidade de objetos apagados\&. Indice 0 = caminhões, indice 1 = carros, indice 2 = motos
.PP
vetor que salva a quantidade de objetos criados\&. Indice 0 = caminhões, indice 1 = carros, indice 2 = motos
.PP
cria 10 carros, caminhões e motos
.PP
cria o objeto legenda
.PP
executa a legenda
.PP
loop infinito de execução do programa
.PP
cria um novo objeto detector de colisões
.PP
cria um novo vetor dinâmico para armazenar as IDs a serem apagadas
.PP
imprime a quantidade de caminhões, carros e motos no mundo atualmente
.PP
detecta colisões entre caminhões e outros veiculos e armazena os IDS dos objetos a serem apagados\&.
.PP
detecta colisões entre carros e outros veiculos e armazena os IDS dos objetos a serem apagados\&.
.PP
detecta colisões entre motos e outros veiculos e armazena os IDS dos objetos a serem apagados\&.
.PP
apaga todos os objetos com as IDs salvas na lista de colisões e incrementa no vetor de apagados total\&.
.PP
popula o mundo de caminhões, conta quantos novos devem ser criados e move os existentes
.PP
cria os novos caminhões e incrementa o vetor de criados total
.PP
popula o mundo de carros, conta quantos novos devem ser criados e move os existentes
.PP
cria os novos carros e incrementa o vetor de criados total
.PP
popula o mundo de motos, conta quantos novos devem ser criados e move os existentes
.PP
cria as novas motos e incrementa o vetor de criados total
.PP
desenha o mundo no console
.PP
exibe quantos veiculos foram apagados e criados durante a execução do programa
.PP
pausa o console pelo tempo determinado
.PP
volta o cursor para o começo do console
.PP
reinicia a matriz do mundo\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Projeto P1 a partir do código fonte\&.
