.TH "Moto" 3 "Quinta, 19 de Abril de 2018" "Version 1.0" "Projeto P1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Moto
.SH SYNOPSIS
.br
.PP
.PP
Derivada de \fBVeiculo\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBMoto\fP ()"
.br
.RI "construtor padrão com tipo da moto aleatória "
.in -1c
.SS "Atributos Protegidos"

.in +1c
.ti -1c
.RI "String \fBtipo\fP"
.br
.in -1c
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "Moto\&.Moto ()"

.PP
construtor padrão com tipo da moto aleatória chama construtor padrão da classe pai 
.SH "Documentação dos dados membro"
.PP 
.SS "String Moto\&.tipo\fC [protected]\fP"


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Projeto P1 a partir do código fonte\&.
