.TH "Mundo" 3 "Quinta, 19 de Abril de 2018" "Version 1.0" "Projeto P1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mundo
.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBMundo\fP ()"
.br
.RI "construtor padrão "
.ti -1c
.RI "void \fBreiniciaMundo\fP ()"
.br
.RI "reinicia a matriz mundo para a matriz padrão "
.ti -1c
.RI "void \fBdesenhaMundo\fP ()"
.br
.RI "imprime no console a matriz com as cores e posições pré definidas "
.ti -1c
.RI "void \fBinsereNoMundo\fP (int x, int y, int tipo)"
.br
.RI "insere um veiculo na matriz do mundo na posição indicada "
.ti -1c
.RI "void \fBvoltaComeco\fP ()"
.br
.RI "volta o cursor no console para o começo "
.ti -1c
.RI "int \fBgetLocalizacao\fP (int x, int y)"
.br
.RI "retorna que tipo esta salvo nas coordenadas indicadas "
.ti -1c
.RI "void \fBpausaMundo\fP ()"
.br
.RI "pausa a execução do programa por 0,5s "
.in -1c
.SS "Atributos Protegidos"

.in +1c
.ti -1c
.RI "int \fBmundo\fP [][]"
.br
.in -1c
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "Mundo\&.Mundo ()"

.PP
construtor padrão cria a matriz mundo padrão 
.SH "Documentação dos métodos"
.PP 
.SS "void Mundo\&.desenhaMundo ()"

.PP
imprime no console a matriz com as cores e posições pré definidas bordas vermelhas
.PP
fundo preto
.PP
fabrica verde
.PP
moto marrom
.PP
carro azul
.PP
caminhao cinza 
.SS "int Mundo\&.getLocalizacao (int x, int y)"

.PP
retorna que tipo esta salvo nas coordenadas indicadas 
.SS "void Mundo\&.insereNoMundo (int x, int y, int tipo)"

.PP
insere um veiculo na matriz do mundo na posição indicada 
.SS "void Mundo\&.pausaMundo ()"

.PP
pausa a execução do programa por 0,5s 
.SS "void Mundo\&.reiniciaMundo ()"

.PP
reinicia a matriz mundo para a matriz padrão 
.SS "void Mundo\&.voltaComeco ()"

.PP
volta o cursor no console para o começo 
.SH "Documentação dos dados membro"
.PP 
.SS "int Mundo\&.mundo[][]\fC [protected]\fP"


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Projeto P1 a partir do código fonte\&.
