.TH "Veiculo" 3 "Quinta, 19 de Abril de 2018" "Version 1.0" "Projeto P1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Veiculo
.SH SYNOPSIS
.br
.PP
.PP
Herdado por \fBCaminhao\fP, \fBCarro\fP e \fBMoto\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBVeiculo\fP (int velocidade, String \fBcor\fP)"
.br
.RI "construtor padrão "
.ti -1c
.RI "void \fBdentroDaFabrica\fP ()"
.br
.RI "define o objeto como dentro da fabrica "
.ti -1c
.RI "void \fBforaDaFabrica\fP ()"
.br
.RI "define o objeto como fora da fabrica "
.ti -1c
.RI "void \fBmove\fP ()"
.br
.RI "move o objeto para uma direção aleatória (direita, esquerda, cima ou baixo), respeitando sua velocidade "
.ti -1c
.RI "int \fBgetX\fP ()"
.br
.RI "volta a posição X "
.ti -1c
.RI "int \fBgetY\fP ()"
.br
.RI "volta a posição Y "
.ti -1c
.RI "boolean \fBgetFabrica\fP ()"
.br
.RI "volta o boleano fabrica (true para dentro e false para fora) "
.ti -1c
.RI "int \fBgetId\fP ()"
.br
.RI "volta a ID do objeto "
.in -1c
.SS "Atributos Protegidos"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "boolean \fBfabrica\fP"
.br
.ti -1c
.RI "String \fBcor\fP"
.br
.in -1c
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "Veiculo\&.Veiculo (int velocidade, String cor)"

.PP
construtor padrão define a cor
.PP
define a velocidade
.PP
cria um objeto aleatorio
.PP
randomiza a posição X
.PP
randomiza a posição Y
.PP
define o objeto como fora da fabrica
.PP
cria um ID aleatório 
.SH "Documentação dos métodos"
.PP 
.SS "void Veiculo\&.dentroDaFabrica ()"

.PP
define o objeto como dentro da fabrica 
.SS "void Veiculo\&.foraDaFabrica ()"

.PP
define o objeto como fora da fabrica 
.SS "boolean Veiculo\&.getFabrica ()"

.PP
volta o boleano fabrica (true para dentro e false para fora) 
.SS "int Veiculo\&.getId ()"

.PP
volta a ID do objeto 
.SS "int Veiculo\&.getX ()"

.PP
volta a posição X 
.SS "int Veiculo\&.getY ()"

.PP
volta a posição Y 
.SS "void Veiculo\&.move ()"

.PP
move o objeto para uma direção aleatória (direita, esquerda, cima ou baixo), respeitando sua velocidade move para a direita
.PP
move para a esquerda
.PP
move para baixo
.PP
move para cima 
.SH "Documentação dos dados membro"
.PP 
.SS "String Veiculo\&.cor\fC [protected]\fP"

.SS "boolean Veiculo\&.fabrica\fC [protected]\fP"

.SS "int Veiculo\&.x\fC [protected]\fP"


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Projeto P1 a partir do código fonte\&.
